name: cleancity
description: A flutter app to report and track garbage and litter in the city.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  location: ^8.0.0
  intl: ^0.20.2

  # Firebase packages
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.1.5

  # State management and utilities
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.0.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  cloudinary_public: ^0.21.0
  url_launcher: ^6.2.5
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/splash/
